# Generated by Django 4.2.2 on 2024-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postlabel',
            field=models.CharField(blank=True, choices=[('POPULAR', 'popular'), ('FAMOUS', 'famous')], max_length=100, null=True),
        ),
    ]
